### ISSUE TITLE
npm linking and sub module requires

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/module-kickstart#3]
At the [current state](https://github.com/gustavnikolaj/module-kickstart/tree/27a8335ae777e0004d63e809908636cffd74d974) of the module boilerplate, it's not possible to require a file in the module when linking it into another project.

The following code is from a consumer project:

```js
var asyncDemo = require('module-kickstart/lib/asyncDemo');

expect(asyncDemo, 'to satisfy', {
  double: expect.it('to be a function');
});
```

That will work fine with the transpiled code, but not with the transpiled-at-runtime code.

We cannot get that to work, as the runtime needs to be set up before loading files that rely on the features (hence the index.js file)

@papandreou If you cannot live with that constraint, I'm afraid we need to take a look at a watcher-based solution that transpiles on change instead of tranpiling when running the code.

**Comment by papandreou** [comment]
I can live with that constraint.

**Comment by gustavnikolaj** [comment]
Good, then I'll just leave it as is.
